name: Deploy Cloud Functions
on:
 push:
   branches:
     - master
   paths:
     — 'functions/**'
jobs:
 build_and_deploy:
   runs-on: ubuntu-latest
   steps:
     — uses: actions/checkout@v2
     — uses: actions/setup-node@v1
       with:
         node-version: 16.x
     — uses: actions/cache@v2
       with:
         path: ~/.npm
         key: ${{ runner.os }}-node-${{ hashFiles('**/functions/package-lock.json') }}
    - name: npm install, build and test
      run: |
        npm install
        cd functions && npm ci
        echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/gcloud.json
        export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json && npx firebase-tools deploy --only functions --json
       